require_relative '../lib/ruby-adjudicator'
Diplomacy.logger = Logger.new RUBY_PLATFORM =~ /mswin|mingw/ ? 'NUL:' : '/dev/null'
require_relative '../lib/adjudicator/state'
require_relative '../lib/graph/graph'
require_relative '../lib/parser/state_parser'
require_relative '../lib/parser/order_parser'
